# Generated by Django 3.1.6 on 2021-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('img', models.CharField(max_length=250, verbose_name='Фото')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.CharField(max_length=5, verbose_name='Цена')),
            ],
        ),
    ]
