# Generated by Django 3.1.6 on 2021-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
