# Generated by Django 3.1.6 on 2021-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210226_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Акция(если нет - оставить по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='main/static/main/img', verbose_name='Фото'),
        ),
    ]
